get http://localhost:3000/user
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2OTE4NTcyMjU5MzYsImV4cCI6MTY5MTg1NzI4NTkzNiwibmFtZSI6IlNlcmdpbyIsImxhc3RuYW1lIjoiSGlkYWxnbyIsImVtYWlsIjoic2VyZ2lvQGNvcnJlby5jb20iLCJyb2xlcyI6WyJBRE1JTiIsIk1FRElDIl19.tfXjbq61gFzkSRq9WZHToNqguhTRT2_s6RP3L3N0yIY