get http://cursonodejs13-env.eba-uzkmmecg.us-east-1.elasticbeanstalk.com/user
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2OTMwNTk1NDU0OTIsImV4cCI6MTY5MzA2MDE0NTQ5MiwibmFtZSI6IlNlcmdpbyIsImxhc3RuYW1lIjoiSGlkYWxnbyIsImVtYWlsIjoic2VyZ2lvQGNvcnJlby5jb20iLCJyb2xlcyI6WyJBRE1JTiIsIk9QRVJBVE9SIl19.gcyawLftK7Sx-vKeeIeCAqc1NiE2FkQbc52kNwtfaVE