get http://cursonodejs13-env.eba-uzkmmecg.us-east-1.elasticbeanstalk.com/user
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2OTMwNjIwMDYyMjAsImV4cCI6MTY5MzA2MjYwNjIyMCwibmFtZSI6IlNlcmdpbyIsImxhc3RuYW1lIjoiSGlkYWxnbyIsImVtYWlsIjoic2VyZ2lvQGNvcnJlby5jb20iLCJyb2xlcyI6WyJBRE1JTiIsIk9QRVJBVE9SIl19.Y6DPUG0468AxcOi5xbS0y8yv4qT3Is9RKIEgjI1X8xg