post http://localhost:3000/user HTTP/1.1
content-type: application/json

{
    "name": "Sergio",
    "lastname": "Hidalgo",
    "email": "sergio@correo.com",
    "password": "123",
    "roles": [1, 2]
}