post http://localhost:3000/user HTTP/1.1
content-type: application/json

{
    "name": "Luis",
    "lastname": "Pérez",
    "email": "juan.perez5@correo.com",
    "password": "12345678",
    "roles": [1, 2]
}