version: '3.8'

services:
  mysql-server:
    image: mysql:8
    container_name: mysql-server
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: course_nodejs
      MYSQL_USER: user
      MYSQL_PASSWORD: 12345
    volumes:
      - vol-course-mysql:/var/lib/mysql
    networks:
      - net-course

  mysql-client:
    image: phpmyadmin:5
    container_name: mysql-client
    restart: always
    ports:
      - '8200:80'
    environment:
      - PMA_ARBITRARY=1
    networks:
      - net-course

  redis-server:
    image: redis:6.0.5-alpine
    container_name: redis-server
    command: redis-server --requirepass TOP_SECRET
    restart: always
    ports:
      - '6379:6379'
    networks:
      - net-course

  redis-client:
    image: rediscommander/redis-commander:latest
    container_name: redis-client
    restart: always
    ports:
      - '8081:8081'
    environment:
      - REDIS_HOST=redis-server
      - REDIS_PORT=6379
      - REDIS_PASSWORD=TOP_SECRET
    depends_on:
      - redis-server
    networks:
      - net-course

  sonarqube:
    image: sonarqube:8-community
    container_name: sonarqube
    ports:
      - '9000:9000'
      - '9092:9092'
    networks:
      - net-course

  locust-master:
    build:
      context: .
      dockerfile: locust/Dockerfile
    container_name: locust-master
    ports:
      - '9000:8089'
    command: '--host http://cursonodejs13-env.eba-uzkmmecg.us-east-1.elasticbeanstalk.com --master'
    networks:
      - net-course

  locust-slave:
    build:
      context: .
      dockerfile: locust/Dockerfile
    command: '--host http://cursonodejs13-env.eba-uzkmmecg.us-east-1.elasticbeanstalk.com --master-host=locust-master --slave'
    networks:
      - net-course

volumes:
  vol-course-mysql:
    name: vol-course-mysql

networks:
  net-course:
    name: net-course
