version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: server-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: course_nodejs
      MYSQL_USER: user
      MYSQL_PASSWORD: 12345
    volumes:
      - vol-course-mysql:/var/lib/mysql

volumes:
  vol-course-mysql:
    name: vol-course-mysql
